'''
Updated 04/17/2020 Andy Cross

This code takes as input all of the swmm files generated by multiple cuph runs, as well as the csv created by contributing_drainage.R. It finds and applies the 
peak flow should be applied to each design point based on results generated from contributing_drainage.R.

To use this code, the SWMM.rpt file names must have the following format:

     2_Ex_100yr_15.108mi^2_...
'''
 
#this is the path to the directory where the .rpt files live
path_to_swmm<-"Z:/MHFD/First Creek/20_Baseline Hydrology/SWMM/Current/"

files<-list.files(path=path_to_swmm,pattern = ".rpt")
design_points<-read.csv("Z:/MHFD/First Creek/888_SCRIPTS/ContributingDrainageData/FCMainDP_AreaCalcs.csv",header=TRUE)
p1=3
p2=4

for(i in files){
  file<-paste(path_to_swmm,i,sep="")
  print(file)
  unl_file<-unlist(strsplit(as.character(file),"_"))
  print(unl_file[])
  g<-unlist(strsplit(as.character(file),"_"))[5]
  f<-unlist(strsplit(g,""))
  f<-f[1:6]
  print(f)
  f<-paste(f[1],f[2],sep="")
  f<-as.character(f)
  print(paste("f",f))
  print(paste("UNLFILE4",unl_file[4]))
  if(as.character(unl_file[4]) == "WQ" || as.character(unl_file[4]) == "2yr" || as.character(unl_file[4]) == "5yr" || as.character(unl_file[4]) == "10yr"){
  pos<-which(as.character(design_points$areaMinor) %in% c(as.character(f)))
  }
  else{
    pos<-which(as.character(design_points$areaMajor) %in% c(as.character(f)))
  }
  print(paste("pos",pos))
  for(u in 1:length(pos)){
    print(paste("posU",pos[u]))
    junction<-as.character(design_points$DP[pos[u]])
    print(paste("junction",junction))
    df<-read.table(file,sep = '\t' )
    for(d in 1:length(df[,1])){
      nodes_search<-strsplit(as.character(df[d,]),"\\s+")
      nodes_search<-unlist(nodes_search)
      if(isTRUE(nodes_search[4] == "nodes")){
        number_nodes<-as.numeric(as.character(nodes_search[6]))
      }
    }
    for(h in 1:length(df[,1])){
      if(as.character("  Node Inflow Summary") == as.character(df[h,])){
        node_summary=as.numeric(as.character(h))
        print(paste("node sum",node_summary))
      }
    }
    node_matrix<-matrix(0,nrow=number_nodes+15,ncol=10)
    junctions=junction
    for(j in node_summary:(node_summary+number_nodes+8)){
      vals<-t(unlist(strsplit(as.character(df[j,]),"\\s+")))
      
      if(isTRUE(vals[2] == junctions)){
        print(paste("vals 5",vals[5]))
        if(isTRUE(unl_file[p1] == "Ex" && unl_file[p2] == "WQ")){
          design_points$XWQ_Existing[pos[u]]<-as.character(vals[5])
          print(vals[5])
          print(paste("vals 5",vals[5]))
        }
        else if(isTRUE(unl_file[p1] == "Fut" && unl_file[p2] == "WQ")){
          design_points$WQ_Future[pos[u]]<-as.character(vals[5])
          print(vals[5])
          print(paste("vals 5",vals[5]))
        }
        
        else if(isTRUE(unl_file[p1] == "Ex" && unl_file[p2] == "2yr")){
          design_points$X2yr_Existing[pos[u]]<-as.character(vals[5])
          print(vals[5])
        }
        else if(isTRUE(unl_file[p1] == "Fut" && unl_file[p2] == "2yr")){
          design_points$X2yr_Future[pos[u]]<-as.character(vals[5])
          print(vals[5])
        }
        
        else if(isTRUE(unl_file[p1] == "Ex" && unl_file[p2] == "5yr")){
          design_points$X5yr_Existing[pos[u]]<-as.character(vals[5])
          print(vals[5])
        }
        else if(isTRUE(unl_file[p1] == "Fut" && unl_file[p2] == "5yr")){
          design_points$X5yr_Future[pos[u]]<-as.character(vals[5])
          print(vals[5])
        }
        else if(isTRUE(unl_file[p1] == "Ex" && unl_file[p2] == "10yr")){
          design_points$X10yr_Existing[pos[u]]<-as.character(vals[5])
          print(vals[5])
        }
        else if(isTRUE(unl_file[p1] == "Fut" && unl_file[p2] == "10yr")){
          design_points$X10yr_Future[pos[u]]<-as.character(vals[5])
          print(vals[5])
        }
        
        else if(isTRUE(unl_file[p1] == "Ex" && unl_file[p2] == "25yr")){
          design_points$X25yr_Existing[pos[u]]<-as.character(vals[5])
          print(vals[5])
        }
        else if(isTRUE(unl_file[p1] == "Fut" && unl_file[p2] == "25yr")){
          design_points$X25yr_Future[pos[u]]<-as.character(vals[5])
          print(vals[5])
        }
        else if(isTRUE(unl_file[p1] == "Fut" && unl_file[p2] == "50yr")){
          design_points$X50yr_Future[pos[u]]<-as.character(vals[5])
          print(vals[5])
        }
        else if(isTRUE(unl_file[p1] == "Ex" && unl_file[p2] == "50yr")){
          design_points$X50yr_Existing[pos[u]]<-as.character(vals[5])
          print(vals[5])
        }
        else if(isTRUE(unl_file[p1] == "Fut" && unl_file[p2] == "100yr")){
          design_points$X100yr_Future[pos[u]]<-as.character(vals[5])
          print(paste("vals 5",vals[5]))
        }
        
        else if(isTRUE(unl_file[p1] == "Ex" && unl_file[p2] == "100yr")){
          design_points$X100yr_Existing[pos[u]]<-as.character(vals[5])
          print(vals[5])
        }
        else if(isTRUE(unl_file[p1] == "Fut" && unl_file[p2] == "500yr")){
          design_points$X500yr_Future[pos[u]]<-as.character(vals[5])
          print(paste("vals 5",vals[5]))
        }
       
        else if(isTRUE(unl_file[p1] == "Ex" && unl_file[p2] == "500yr")){
          design_points$X500yr_Existing[pos[u]]<-as.character(vals[5])
          print(vals[5])
        }
      }
   }
  }
}
#design<-read.csv("Z:/MHFD/First Creek/2_Documents/03_Deliverables/01_PeakFlows/PeakFlow_All.csv",header=TRUE)
#del<-matrix(0,nrow=2000,ncol=1)
#for(i in 1:length(design$DP)){
#  pos<-which(as.character(design_points$ï..DP) %in% c(as.character(design$DP[i])))
#  del[i]<-pos
#}
#z<-which(del==0)
#del<-del[-z]
#design_points<-design_points[-del,]
write.csv(design_points,"Z:/MHFD/First Creek/20_Baseline Hydrology/FC_GIS_Submittal/GIS_Submittal_V2/Data/UpdatedPeakFlows_20200128.csv")







